### ISSUE TITLE
Feature: Follow service

### ISSUE THREAD

**Issue by tobinstultiens** [tobinstultiens/sharerecipe#2]
### Description
As a user, I'd like to be able to follow other people, in order to follow what they're posting.

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should be able to follow a user.
- [x] Should be able to unfollow a user.
- [x] Should be able to see what they're posting.

Also, here are a few points that need to be addressed:

1. Constraint 1: A user can't follow themselves.

### Tasks
- [x] Follow
- [x] UnFollow
