### ISSUE TITLE
Feature: Profiles

### ISSUE THREAD

**Issue by tobinstultiens** [tobinstultiens/sharerecipe#4]
### Description
As a user, I'd like to have a profile, in order to demonstrate what I'm about to attract people to follow me.

### Acceptance Criteria
Reference: Done-Done Checklist
- [x] Should be able to create a profile.
- [x] Should be able to edit profile picture.
- [x] Should be able to edit profile description.
- [x] Should be able to get a profile.

Also, here are a few points that need to be addressed:

1. Constraint 1: Only the owner of the account can change these values

### Tasks
- [x] Create profile service
- [x] Store profiles
- [x] Edit profiles
- [x] Retrieve profiles
