### ISSUE TITLE
Feature: User Moderation

### ISSUE THREAD

**Issue by tobinstultiens** [tobinstultiens/sharerecipe#5]
### Description
As a Moderator, I'd like to be able to moderate the users of my platform, in order to be able to ban people who are misusing the platform.

### Acceptance Criteria
Reference: Done-Done Checklist
- [ ] Should be able to ban users.
- [ ] Should be able to unban users.
- [ ] Should be able to remove kweets.

Also, here are a few points that need to be addressed:

1. Constraint 1:

### Tasks
- [ ] Ban users
- [ ] unban users
- [ ] remove kweets

**Comment by tobinstultiens** [comment]
Dropped since I'm not implementing this
